# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SylDoc', '0002_auto_20160911_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('gold', models.CharField(max_length=255)),
                ('logindate', models.CharField(max_length=255)),
                ('iconpath', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('usersign', models.CharField(max_length=255)),
                ('expend', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('count', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='webmanager',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
