# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SylDoc', '0004_auto_20160912_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
