# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SylDoc', '0005_auto_20160912_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='expend',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='iconpath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='usersign',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='webindex',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
