# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SylDoc', '0006_auto_20160912_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cls', models.CharField(default='', max_length=255)),
                ('subcls', models.CharField(default='', max_length=255)),
                ('style', models.CharField(default='', max_length=255)),
                ('dynasty', models.CharField(default='', max_length=255)),
                ('describe', models.TextField(default='')),
                ('word_title', models.CharField(default='', max_length=255)),
                ('word_describe', models.CharField(default='', max_length=255)),
                ('auth_name', models.CharField(default='', max_length=255)),
                ('auth_describe', models.TextField(default='')),
                ('check_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('bid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uploader', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField()),
                ('see', models.IntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('worse', models.IntegerField(default=0)),
                ('search_see', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
            ],
        ),
    ]
